data_dir: /data/zeynep/HIN_data/


pfam: [PF12799]

RNAseq: [RNA-1_fastqc.zip, RNA-2_fastqc.zip]

DNAseq: [pacbio.fastq.gz, nanopore.fastq.gz,
      illumina_run1_R1.fastq.gz,illumina_run1_R2.fastq.gz,
      illumina_run2_R1.fastq.gz, illumina_run2_R2.fastq.gz,
      illumina_run3_R1.fastq.gz, illumina_run3_R2.fastq.gz]

reads: [pacbio, nanopore,
         illumina_run1_R1, illumina_run1_R2,
         illumina_run2_R1, illumina_run2_R2,
         illumina_run3_R1, illumina_run3_R2]

ill: [illumina_run1,
      illumina_run2
      illumina_run3]

nano: [nanopore]
pac: [pacbio]


illumina_run1: [illumina_run1_R1.fastq.gz, illumina_run1_R2.fastq.gz]
illumina_run2: [illumina_run2_R1.fastq.gz, illumina_run2_R2.fastq.gz]
illumina_run3: [illumina_run3_R1.fastq.gz, illumina_run3_R2.fastq.gz]

nanopore: [nanopore]
pacbio: [pacbio]

